// import {colorPrimary} from '@Contexts/color';

import { colorPrimary } from "./Semantic";

export const colorBackgroundLight = {
  "bg-dot": colorPrimary.CoralRed["coralred/500"],
  "bg-primary": colorPrimary.Neutral["base/white"],
  "bg-primary-cards": colorPrimary.Neutral["base/white"],
  "bg-secondary": colorPrimary.Neutral["neutral/50"],
  "bg-tertiary": colorPrimary.Neutral["neutral/100"],
  "bg-quaternary": colorPrimary.Neutral["neutral/200"],
  "bg-senary": colorPrimary.Neutral["neutral/300"],
  "bg-solid-primary": colorPrimary.Neutral["neutral/900"],
  "bg-solid-secondary": colorPrimary.Neutral["neutral/800"],
  "bg-solid-tertiary": colorPrimary.Neutral["neutral/700"],
  "bg-solid-quarternary": colorPrimary.Neutral["neutral/500"],
  "bg-brand-primary": colorPrimary.Primary["primary/50"],
  "bg-brand-secondary": colorPrimary.Primary["primary/100"],
  "bg-brand-tertiary": colorPrimary.Primary["primary/200"],
  "bg-brand-quaternary": colorPrimary.Primary["primary/500"],
  "bg-brand-quinary": colorPrimary.Primary["primary/600"],
  "bg-brand-senary": colorPrimary.Primary["primary/700"],
  "bg-success-primary": colorPrimary.Success["success/50"],
  "bg-success-secondary": colorPrimary.Success["success/100"],
  "bg-success-tertiary": colorPrimary.Success["success/500"],
  "bg-success-quarternary": colorPrimary.Success["success/600"],
  "bg-success-senery": colorPrimary.Success["success/700"],
  "bg-warning": colorPrimary.Warning["warning/500"],
  "bg-error-primary": colorPrimary.Error["error/50"],
  "bg-error-secondary": colorPrimary.Error["error/100"],
  "bg-error-tertiary": colorPrimary.Error["error/200"],
  "bg-error-quarternary": colorPrimary.Error["error/600"],
  "bg-error-quinary": colorPrimary.Error["error/700"],
  "bg-error-senary": colorPrimary.Error["error/800"],
};

export const colorBackgroundDark = {
  "bg-dot": colorPrimary.CoralRed["coralred/500"],
  "bg-primary": colorPrimary.Neutral["neutral/900"],
  "bg-primary-cards": colorPrimary.Neutral["neutral/800"],
  "bg-secondary": colorPrimary.Neutral["neutral/800"],
  "bg-tertiary": colorPrimary.Neutral["neutral/700"],
  "bg-quaternary": colorPrimary.Neutral["neutral/700"],
  "bg-senary": colorPrimary.Neutral["neutral/700"],
  "bg-solid-primary": colorPrimary.Neutral["neutral/50"],
  "bg-solid-secondary": colorPrimary.Neutral["neutral/300"],
  "bg-solid-tertiary": colorPrimary.Neutral["neutral/200"],
  "bg-solid-quarternary": colorPrimary.Neutral["neutral/400"],
  "bg-brand-primary": colorPrimary.Primary["primary/900"],
  "bg-brand-secondary": colorPrimary.Primary["primary/800"],
  "bg-brand-tertiary": colorPrimary.Primary["primary/700"],
  "bg-brand-quaternary": colorPrimary.Primary["primary/400"],
  "bg-brand-quinary": colorPrimary.Primary["primary/300"],
  "bg-brand-senary": colorPrimary.Primary["primary/200"],
  "bg-success-primary": colorPrimary.Success["success/900"],
  "bg-success-secondary": colorPrimary.Success["success/800"],
  "bg-success-tertiary": colorPrimary.Success["success/400"],
  "bg-success-quarternary": colorPrimary.Success["success/300"],
  "bg-success-senery": colorPrimary.Success["success/200"],
  "bg-warning": colorPrimary.Warning["warning/900"],
  "bg-error-primary": colorPrimary.Error["error/900"],
  "bg-error-secondary": colorPrimary.Error["error/800"],
  "bg-error-tertiary": colorPrimary.Error["error/700"],
  "bg-error-quarternary": colorPrimary.Error["error/300"],
  "bg-error-quinary": colorPrimary.Error["error/200"],
  "bg-error-senary": colorPrimary.Error["error/100"],
};

export const colorBackground = {
  light: colorBackgroundLight,
  dark: colorBackgroundDark,
};
