import { colorPrimary } from "./Semantic";

export const colorButtonLight = {
  Primary: {
    "fg-button-primary": colorPrimary.Neutral["base/white"],
    "fg-button-primary-disabled": colorPrimary.Neutral["neutral/400"],
    "bg-button-primary": colorPrimary.Primary["primary/500"],
    "bg-button-primary-hover": colorPrimary.Primary["primary/600"],
    "bg-button-primary-click": colorPrimary.Primary["primary/700"],
    "bg-button-primary-disabled": colorPrimary.Neutral["neutral/100"],
  },
  Secondary: {
    "fg-button-secondary": colorPrimary.Primary["primary/500"],
    "fg-button-secondary-hover": colorPrimary.Primary["primary/600"],
    "fg-button-secondary-click": colorPrimary.Primary["primary/700"],
    "fg-button-secondary-disabled": colorPrimary.Neutral["neutral/400"],

    "bg-button-secondary": colorPrimary.Neutral["base/white"],
    "bg-button-secondary-hover": colorPrimary.Primary["primary/50"],
    "bg-button-secondary-click": colorPrimary.Primary["primary/100"],

    "bg-button-secondary-disabled": colorPrimary.Neutral["base/white"],
    "border-button-secondary": colorPrimary.Primary["primary/500"],
    "border-button-secondary-hover": colorPrimary.Primary["primary/600"],
    "border-button-secondary-click": colorPrimary.Primary["primary/700"],
    "border-button-secondary-disabled": colorPrimary.Neutral["neutral/200"],
  },
  Tertiary: {
    "fg-button-tertiary": colorPrimary.Neutral["neutral/700"],
    "fg-button-tertiary-hover": colorPrimary.Neutral["neutral/800"],
    "fg-button-tertiary-click": colorPrimary.Neutral["neutral/900"],
    "fg-button-tertiary-disabled": colorPrimary.Neutral["neutral/400"],

    "bg-button-tertiary": colorPrimary.Neutral["base/white"],
    "bg-button-tertiary-hover": colorPrimary.Neutral["neutral/50"],
    "bg-button-tertiary-click": colorPrimary.Neutral["neutral/100"],
    "bg-button-tertiary-disabled": colorPrimary.Neutral["base/white"],
    "border-button-tertiary": colorPrimary.Neutral["neutral/300"],
    "border-button-tertiary-disabled": colorPrimary.Neutral["neutral/200"],
  },
  Link_01: {
    "fg-button-link01": colorPrimary.Primary["primary/500"],
    "fg-button-link01-hover": colorPrimary.Primary["primary/600"],
    "fg-button-link01-click": colorPrimary.Primary["primary/700"],
    "fg-button-link01-disabled": colorPrimary.Neutral["neutral/400"],
    "bg-button-link01": colorPrimary.Primary["primary/50"],
  },
  Link_02: {
    "fg-button-link02": colorPrimary.Neutral["neutral/700"],
    "fg-button-link02-hover": colorPrimary.Neutral["neutral/800"],
    "fg-button-link02-click": colorPrimary.Neutral["neutral/900"],
    "fg-button-link01-disabled": colorPrimary.Neutral["neutral/400"],
    "bg-button-link02": colorPrimary.Neutral["neutral/50"],
  },
  Destructive_primary: {
    "fg-button-destructive-primary": colorPrimary.Neutral["base/white"],
    "fg-button-destructive-primary-disabled": colorPrimary.Neutral["neutral/400"],
    "bg-button-destructive-primary": colorPrimary.Error["error/600"],
    "bg-button-destructive-primary-hover": colorPrimary.Error["error/700"],
    "bg-button-destructive-primary-click": colorPrimary.Error["error/800"],
    "bg-button-destructive-primary-disabled": colorPrimary.Neutral["neutral/100"],
  },

  Destructive_secondary: {
    "fg-button-destructive-secondary": colorPrimary.Error["error/600"],
    "fg-button-destructive-secondary-hover": colorPrimary.Error["error/700"],
    "fg-button-destructive-secondary-click": colorPrimary.Error["error/800"],
    "fg-button-destructive-secondary-disabled": colorPrimary.Neutral["neutral/400"],
    "border-button-destructive-secondary": colorPrimary.Error["error/600"],
    "border-button-destructive-secondary-hover": colorPrimary.Error["error/700"],
    "border-button-destructive-secondary-click": colorPrimary.Error["error/800"],
    "border-button-destructive-secondary-disabled": colorPrimary.Neutral["neutral/200"],
    "bg-button-destructive-secondary": colorPrimary.Neutral["base/white"],
    "bg-button-destructive-secondary-hover": colorPrimary.Error["error/50"],
    "bg-button-destructive-secondary-click": colorPrimary.Error["error/100"],
    "bg-button-destructive-secondary-disabled": colorPrimary.Neutral["base/white"],
  },
  Destructive_tertiary: {
    "fg-button-destructive-tertiary": colorPrimary.Error["error/600"],
    "fg-button-destructive-tertiary-hover": colorPrimary.Error["error/700"],
    "fg-button-destructive-tertiary-click": colorPrimary.Error["error/800"],
    "fg-button-destructive-tertiary-disabled": colorPrimary.Neutral["neutral/400"],
    "bg-button-destructive-tertiary": colorPrimary.Neutral["base/white"],
    "bg-button-destructive-tertiary-hover": colorPrimary.Error["error/50"],
    "bg-button-destructive-tertiary-click": colorPrimary.Error["error/100"],
    "bg-button-destructive-tertiary-disabled": colorPrimary.Neutral["base/white"],
    "border-button-destructive-tertiary": colorPrimary.Error["error/200"],
    "border-button-destructive-tertiary-hover": colorPrimary.Error["error/300"],
    "border-button-destructive-tertiary-click": colorPrimary.Error["error/400"],
    "border-button-destructive-tertiary-disabled": colorPrimary.Neutral["neutral/200"],
  },
  Destructive_link_01: {
    "fg-button-destructive-link01": colorPrimary.Error["error/600"],
    "fg-button-destructive-link01-hover": colorPrimary.Error["error/700"],
    "fg-button-destructive-link01-click": colorPrimary.Error["error/800"],
    "fg-button-destructive-link01-disabled": colorPrimary.Neutral["neutral/400"],
    "bg-button-destructive-link01": colorPrimary.Error["error/50"],
  },
};

export const colorButtonDark = {
  Primary: {
    "fg-button-primary": colorPrimary.Neutral["base/white"],
    "fg-button-primary-disabled": colorPrimary.Neutral["neutral/500"],
    "bg-button-primary": colorPrimary.Primary["primary/500"],
    "bg-button-primary-hover": colorPrimary.Primary["primary/600"],
    "bg-button-primary-click": colorPrimary.Primary["primary/700"],
    "bg-button-primary-disabled": colorPrimary.Primary["primary/800"],
  },
  Secondary: {
    "fg-button-secondary": colorPrimary.Primary["primary/400"],
    "fg-button-secondary-hover": colorPrimary.Primary["primary/300"],
    "fg-button-secondary-click": colorPrimary.Primary["primary/200"],
    "fg-button-secondary-disabled": colorPrimary.Neutral["neutral/500"],

    "bg-button-secondary": colorPrimary.Neutral["neutral/900"],
    "bg-button-secondary-hover": colorPrimary.Primary["primary/900"],
    "bg-button-secondary-click": colorPrimary.Primary["primary/800"],

    "bg-button-secondary-disabled": colorPrimary.Neutral["neutral/900"],
    "border-button-secondary": colorPrimary.Primary["primary/400"],
    "border-button-secondary-hover": colorPrimary.Primary["primary/300"],
    "border-button-secondary-click": colorPrimary.Primary["primary/200"],
    "border-button-secondary-disabled": colorPrimary.Neutral["neutral/700"],
  },

  Tertiary: {
    "fg-button-tertiary": colorPrimary.Neutral["neutral/200"],
    "fg-button-tertiary-hover": colorPrimary.Neutral["neutral/100"],
    "fg-button-tertiary-click": colorPrimary.Neutral["neutral/50"],
    "fg-button-tertiary-disabled": colorPrimary.Neutral["neutral/500"],
    "bg-button-tertiary": colorPrimary.Neutral["neutral/900"],
    "bg-button-tertiary-hover": colorPrimary.Neutral["neutral/800"],
    "bg-button-tertiary-click": colorPrimary.Neutral["neutral/700"],
    "bg-button-tertiary-disabled": colorPrimary.Neutral["neutral/900"],
    "border-button-tertiary": colorPrimary.Neutral["neutral/600"],
    "border-button-tertiary-disabled": colorPrimary.Neutral["neutral/700"],
  },

  Link_01: {
    "fg-button-link01": colorPrimary.Primary["primary/400"],
    "fg-button-link01-hover": colorPrimary.Primary["primary/300"],
    "fg-button-link01-click": colorPrimary.Primary["primary/200"],
    "fg-button-link01-disabled": colorPrimary.Neutral["neutral/500"],
    "bg-button-link01": colorPrimary.Primary["primary/800"],
  },
  Link_02: {
    "fg-button-link02": colorPrimary.Neutral["neutral/200"],
    "fg-button-link02-hover": colorPrimary.Neutral["neutral/100"],
    "fg-button-link02-click": colorPrimary.Neutral["neutral/50"],
    "fg-button-link01-disabled": colorPrimary.Neutral["neutral/500"],
    "bg-button-link02": colorPrimary.Neutral["neutral/800"],
  },
  Destructive_primary: {
    "fg-button-destructive-primary": colorPrimary.Neutral["base/white"],
    "fg-button-destructive-primary-disabled": colorPrimary.Neutral["neutral/500"],
    "bg-button-destructive-primary": colorPrimary.Error["error/600"],
    "bg-button-destructive-primary-hover": colorPrimary.Error["error/700"],
    "bg-button-destructive-primary-click": colorPrimary.Error["error/800"],
    "bg-button-destructive-primary-disabled": colorPrimary.Neutral["neutral/800"],
  },

  Destructive_secondary: {
    "fg-button-destructive-secondary": colorPrimary.Error["error/200"],
    "fg-button-destructive-secondary-hover": colorPrimary.Error["error/100"],
    "fg-button-destructive-secondary-click": colorPrimary.Error["error/50"],
    "fg-button-destructive-secondary-disabled": colorPrimary.Neutral["neutral/500"],
    "border-button-destructive-secondary": colorPrimary.Error["error/800"],
    "border-button-destructive-secondary-hover": colorPrimary.Error["error/700"],
    "border-button-destructive-secondary-click": colorPrimary.Error["error/600"],
    "border-button-destructive-secondary-disabled": colorPrimary.Neutral["neutral/700"],
    "bg-button-destructive-secondary": colorPrimary.Error["error/950"],
    "bg-button-destructive-secondary-hover": colorPrimary.Error["error/900"],
    "bg-button-destructive-secondary-click": colorPrimary.Error["error/800"],
    "bg-button-destructive-secondary-disabled": colorPrimary.Neutral["neutral/900"],
  },

  Destructive_tertiary: {
    "fg-button-destructive-tertiary": colorPrimary.Error["error/200"],
    "fg-button-destructive-tertiary-hover": colorPrimary.Error["error/100"],
    "fg-button-destructive-tertiary-click": colorPrimary.Error["error/500"],
    "fg-button-destructive-tertiary-disabled": colorPrimary.Neutral["neutral/500"],
    "bg-button-destructive-tertiary": colorPrimary.Neutral["neutral/900"],
    "bg-button-destructive-tertiary-hover": colorPrimary.Error["error/900"],
    "bg-button-destructive-tertiary-click": colorPrimary.Error["error/800"],
    "bg-button-destructive-tertiary-disabled": colorPrimary.Neutral["neutral/900"],
    "border-button-destructive-tertiary": colorPrimary.Error["error/800"],
    "border-button-destructive-tertiary-hover": colorPrimary.Error["error/700"],
    "border-button-destructive-tertiary-click": colorPrimary.Error["error/600"],
    "border-button-destructive-tertiary-disabled": colorPrimary.Neutral["neutral/700"],
  },
  Destructive_link_01: {
    "fg-button-destructive-link01": colorPrimary.Error["error/600"],
    "fg-button-destructive-link01-hover": colorPrimary.Error["error/700"],
    "fg-button-destructive-link01-click": colorPrimary.Error["error/800"],
    "fg-button-destructive-link01-disabled": colorPrimary.Neutral["neutral/400"],
    "bg-button-destructive-link01": colorPrimary.Error["error/50"],
  },
};

export const colorButton = {
  light: colorButtonLight,
  dark: colorButtonDark,
};
